# Generated by Django 3.1.4 on 2020-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chefdepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('prenom', models.CharField(max_length=50, null='true')),
                ('mail', models.CharField(max_length=50, null='true')),
            ],
        ),
        migrations.CreateModel(
            name='chefsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('prenom', models.CharField(max_length=50, null='true')),
                ('mail', models.CharField(max_length=50, null='true')),
                ('section', models.CharField(max_length=20, null='true')),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('prenom', models.CharField(max_length=50, null='true')),
                ('mail', models.CharField(max_length=50, null='true')),
            ],
        ),
    ]
