# Generated by Django 3.1.4 on 2020-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('électricité', 'électricité'), ('hydrolique', 'hydrolique'), ('mécanique', 'mécanique')], max_length=50, null='true')),
            ],
        ),
    ]
