# Generated by Django 3.1.4 on 2020-12-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0003_auto_20201217_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefsection',
            name='section',
            field=models.OneToOneField(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section'),
        ),
    ]
