# Generated by Django 3.1.4 on 2020-12-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0004_auto_20201217_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefsection',
            name='section',
        ),
        migrations.AlterField(
            model_name='chefsection',
            name='nom',
            field=models.CharField(choices=[('électricité', 'électricité'), ('hydrolique', 'hydrolique'), ('mécanique', 'mécanique')], max_length=50, null='true'),
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
