# Generated by Django 3.1.4 on 2020-12-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0006_auto_20201217_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('électricité', 'électricité'), ('hydrolique', 'hydrolique'), ('mécanique', 'mécanique')], max_length=50, null='true')),
            ],
        ),
        migrations.AlterField(
            model_name='chefsection',
            name='section',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section'),
        ),
    ]
