# Generated by Django 3.1.4 on 2020-12-17 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0008_auto_20201217_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='section',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section'),
            preserve_default='true',
        ),
    ]
