# Generated by Django 3.1.4 on 2020-12-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0009_utilisateur_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ouvriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('prenom', models.CharField(max_length=50, null='true')),
                ('disponible', models.BinaryField(null='true')),
                ('section', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section')),
            ],
        ),
    ]
