# Generated by Django 3.1.4 on 2020-12-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0011_auto_20201217_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='demandeTravailChefSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null='true')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chefsection', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.chefdepartement')),
            ],
        ),
        migrations.CreateModel(
            name='localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
            ],
        ),
        migrations.AlterField(
            model_name='ouvrier',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='outillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('Quantité', models.IntegerField(null='true')),
                ('section', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section')),
            ],
        ),
        migrations.CreateModel(
            name='ordreTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null='true')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demandeTravailChefSection', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.demandetravailchefsection')),
                ('outillage', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.outillage')),
                ('ouvrier', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.ouvrier')),
                ('section', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section')),
            ],
        ),
        migrations.CreateModel(
            name='equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null='true')),
                ('localisation', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.localisation')),
                ('section', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.section')),
            ],
        ),
        migrations.CreateModel(
            name='demandeTravailUtilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null='true')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chefsection', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.chefsection')),
                ('utilisateur', models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='demandetravailchefsection',
            name='localisation',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.localisation'),
        ),
    ]
