# Generated by Django 3.1.4 on 2020-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0013_auto_20201219_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordretravail',
            name='ouvrier',
            field=models.ManyToManyField(to='webSite.ouvrier'),
        ),
    ]
