# Generated by Django 3.1.4 on 2020-12-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0014_auto_20201219_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordretravail',
            name='description',
            field=models.CharField(max_length=500, null='true'),
        ),
        migrations.RemoveField(
            model_name='ordretravail',
            name='outillage',
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='outillage',
            field=models.ManyToManyField(to='webSite.outillage'),
        ),
    ]
