# Generated by Django 3.1.4 on 2020-12-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0015_auto_20201219_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outillage',
            name='section',
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='demandeTravailUtilisateur',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='webSite.demandetravailutilisateur'),
            preserve_default='true',
        ),
    ]
